"""empty message

Revision ID: 469a913c6d11
Revises: 88e4456dd1ba
Create Date: 2024-11-26 07:54:35.797657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469a913c6d11'
down_revision: Union[str, None] = '88e4456dd1ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon_discount_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('coupon_id', sa.UUID(), nullable=False),
    sa.Column('min_cart_amount', sa.Float(), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('discount_percentage', sa.Float(), nullable=True),
    sa.Column('discount_fixed', sa.Float(), nullable=True),
    sa.Column('applicable_product_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('buy_product_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('get_product_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.PrimaryKeyConstraint('coupon_id')
    )
    op.create_unique_constraint(None, 'coupons', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='unique')
    op.drop_table('coupon_discount_details')
    # ### end Alembic commands ###
